In [1]:
import pandas as pd
import numpy as np

    Данные представляют собой набор характеристик вина.
    Структура данных:

    Class: Класс вина (целочисленный). Значения: 1, 2, 3.
    Alcohol: Содержание алкоголя (вещественный).
    Malic Acid: Количество яблочной кислоты (вещественный).
    Ash: Зольность (вещественный).
    Alcalinity of Ash: Щелочность золы (вещественный).
    Magnesium: Количество магния (вещественный).
    Total Phenols: Общее количество фенолов (вещественный).
    Flavanoids: Количество флавоноидов (вещественный).
    Nonflavanoid Phenols: Количество неплавоноидных фенолов (вещественный).
    Proanthocyanins: Количество протоантоцианов (вещественный).
    Color Intensity: Интенсивность цвета (вещественный).
    Hue: Оттенок (вещественный).
    OD280/OD315 of Diluted Wines: OD280/OD315 разбавленного вина (вещественный).
    Proline: Количество пролина (вещественный).

In [2]:
# 2.1 вывод таблицы
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data'
column_names = ['Class', 'Alcohol', 'Malic Acid', 'Ash', 'Alcalinity of Ash', 'Magnesium', 'Total Phenols', 'Flavanoids', 
                'Nonflavanoid Phenols', 'Proanthocyanins', 'Color Intensity', 'Hue', 'OD280/OD315 of Diluted Wines', 'Proline']
df = pd.read_csv(url, header=None, names=column_names)
df.columns = column_names
df

,Class,Alcohol,Malic Acid,Ash,Alcalinity of Ash,Magnesium,Total Phenols,Flavanoids,Nonflavanoid Phenols,Proanthocyanins,Color Intensity,Hue,OD280/OD315 of Diluted Wines,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [3]:
# 2.2вывод первых 5 элементов таблицы
df.head(5)

,Class,Alcohol,Malic Acid,Ash,Alcalinity of Ash,Magnesium,Total Phenols,Flavanoids,Nonflavanoid Phenols,Proanthocyanins,Color Intensity,Hue,OD280/OD315 of Diluted Wines,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [4]:
# 2.3 вывод последних 5 элементов таблицы
df.tail(5)

,Class,Alcohol,Malic Acid,Ash,Alcalinity of Ash,Magnesium,Total Phenols,Flavanoids,Nonflavanoid Phenols,Proanthocyanins,Color Intensity,Hue,OD280/OD315 of Diluted Wines,Proline
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.7,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.3,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.2,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.3,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.2,0.61,1.60,560

In [5]:
# 2.4 использовать функцию describe()
df.describe()

,Class,Alcohol,Malic Acid,Ash,Alcalinity of Ash,Magnesium,Total Phenols,Flavanoids,Nonflavanoid Phenols,Proanthocyanins,Color Intensity,Hue,OD280/OD315 of Diluted Wines,Proline
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,1.938202,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258
std,0.775035,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474
min,1.000000,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000
25%,1.000000,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000
50%,2.000000,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000
75%,3.000000,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000
max,3.000000,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000

In [6]:
# 2.5 считывание значения конкретной ячейки (с конкретным индексом из конкретной колонки) всеми известными вам способами
df.iloc[1]['Alcohol']

13.2

In [7]:
df.at[1,'Alcohol']

13.2

In [8]:
df['Alcohol'].values[1]

13.2

In [ ]:
# 2.6 фильтрация строк по диапазону индекса
start = int(input("Введите начало диапазона: "))
end = int(input("Введите конец диапазона: ")) + 1
range_list = []
for i in range(start, end):
    range_list.append(i)
df[df.index.isin(range_list)]

In [ ]:
# 2.7 фильтрация набора данных по какому-либо условию
# Отсортировано по проценту алкоголя, классу и насыщенности цвета
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data'
df1 = df[(df['Alcohol'] > 12) & (df['Class'] == 2) & (df['Hue'] < 1.05)]
df1

In [ ]:
# 2.8) Удаление строк с пропущенными значениями
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data'
df2 = pd.read_csv(url, header=None)
df2 = df.dropna()
df2

In [ ]:
# 2.9) создание нового поля вычисленного на основе значений других полей:
# 2.9.1) через выражение на базе имеющихся колонок
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data'
column_names = ['Class', 'Alcohol', 'Malic Acid', 'Ash', 'Alcalinity of Ash', 'Magnesium', 'Total Phenols', 'Flavanoids', 
                'Nonflavanoid Phenols', 'Proanthocyanins', 'Color Intensity', 'Hue', 'OD280/OD315 of Diluted Wines', 'Proline']
df1 = pd.read_csv(url, header=None, names=column_names)
df1.columns = column_names
df1['Alcohol_Level'] = pd.cut(df['Alcohol'], bins=[0, 12, 14, 100], labels=['Low', 'Medium', 'High'])
df1

In [ ]:
# 2.9.2) через DataFrame.apply
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data'
column_names = ['Class', 'Alcohol', 'Malic Acid', 'Ash', 'Alcalinity of Ash', 'Magnesium', 'Total Phenols', 'Flavanoids', 
                'Nonflavanoid Phenols', 'Proanthocyanins', 'Color Intensity', 'Hue', 'OD280/OD315 of Diluted Wines', 'Proline']
df1 = pd.read_csv(url, header=None, names=column_names)
df1.columns = column_names
def get_color_intensity_level(row):
    if row['Color Intensity'] < 5:
        return 'Low'
    else:
        return 'High'
    
df1['Color_Intensity_Level'] = df.apply(get_color_intensity_level, axis=1)
df1

In [ ]:
# 2.9.3) через Series.apply
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data'
column_names = ['Class', 'Alcohol', 'Malic Acid', 'Ash', 'Alcalinity of Ash', 'Magnesium', 'Total Phenols', 'Flavanoids', 
                'Nonflavanoid Phenols', 'Proanthocyanins', 'Color Intensity', 'Hue', 'OD280/OD315 of Diluted Wines', 'Proline']
df1 = pd.read_csv(url, header=None, names=column_names)
df1['Alcohol'] = df1['Alcohol'].astype(int)
alc_list = list(df1['Alcohol'])
a = pd.Series(alc_list)

def get_alcohol_level(alcohol):
    if alcohol < 12:
        return 'Low'
    elif alcohol >= 12 and alcohol < 14:
        return 'Medium'
    else:
        return 'High'

a.apply(get_alcohol_level)

In [ ]:
# 2.10) сортировка по какому-либо из полей
# 2.11) вычислить несколько статистик по колонкам.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data'
column_names = ['Class', 'Alcohol', 'Malic Acid', 'Ash', 'Alcalinity of Ash', 'Magnesium', 'Total Phenols', 'Flavanoids', 
                'Nonflavanoid Phenols', 'Proanthocyanins', 'Color Intensity', 'Hue', 'OD280/OD315 of Diluted Wines', 'Proline']
df1 = pd.read_csv(url, header=None, names=column_names)
mean_alcohol = df1['Alcohol'].mean()
min_alcohol = df1['Alcohol'].min()
max_alcohol = df1['Alcohol'].max()
print("Среднее значение: ", mean_alcohol)
print("Минимальное значение: ", min_alcohol)
print("Максимальное значение: ", max_alcohol)

In [ ]:
# 2.12) .value_counts()
df1['Alcohol'].value_counts()

In [ ]:
# 2.13) Вывод уникальных значений колонки через .unique()
df1['Alcohol'].unique()

In [ ]:
# 2.14) Удалите текущий индекс и создайте новый индекс на базе новой колонки, которая для этого лучше всего подходит
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data'
column_names = ['Class', 'Alcohol', 'Malic Acid', 'Ash', 'Alcalinity of Ash', 'Magnesium', 'Total Phenols', 'Flavanoids', 
                'Nonflavanoid Phenols', 'Proanthocyanins', 'Color Intensity', 'Hue', 'OD280/OD315 of Diluted Wines', 'Proline']
df1 = pd.read_csv(url, header=None, names=column_names)
df1 = df1.set_index('Class')
df1